services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - vacation_plan_api
      - db
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d

  db:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=vacation_plan_api
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db

  vacation_plan_api:
    container_name: vacation_plan_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
